package com.ioter.uhfscan.data.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ioter.uhfscan.data.greendao.EpcModel;

import com.ioter.uhfscan.data.greendao.dao.EpcModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig epcModelDaoConfig;

    private final EpcModelDao epcModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        epcModelDaoConfig = daoConfigMap.get(EpcModelDao.class).clone();
        epcModelDaoConfig.initIdentityScope(type);

        epcModelDao = new EpcModelDao(epcModelDaoConfig, this);

        registerDao(EpcModel.class, epcModelDao);
    }
    
    public void clear() {
        epcModelDaoConfig.clearIdentityScope();
    }

    public EpcModelDao getEpcModelDao() {
        return epcModelDao;
    }

}
